name: Build Linux
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cmake
          cmake --version
      - name: Build Banana
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./Banana
